<?php
// Database configuration generated by installer on 2026-10-01 13:46:48
define('DB_HOST', '127.0.0.1');
define('DB_PORT', '3306');
define('DB_NAME', 'gaming_platform');
define('DB_USER', 'gaming_user');
define('DB_PASS', 'gaming_secure_pass_2026');
define('DB_CHARSET', 'utf8mb4');
